version: 2.1

workspace_root: &workspace_root ~/workspace
node_modules_dir: &node_modules_dir node_modules/
yarnpkg_cache_dir: &yarnpkg_cache_dir ./.cache/yarn

executors:
  node_lts:
    working_directory: *workspace_root
    environment:
      YARN_CACHE_FOLDER: *yarnpkg_cache_dir
    docker:
      - image: circleci/node:8.16.0

  node_latest:
    working_directory: *workspace_root
    environment:
      YARN_CACHE_FOLDER: *yarnpkg_cache_dir
    docker:
      - image: circleci/node:11.15.0

commands:
  cmd_restore_cache:
    steps:
      - restore_cache:
        keys:
          - v1-dep-{{ arch }}-{{ checksum "yarn.lock" }}

  cmd_save_cache:
    steps:
      - save_cache:
        key: v1-dep-{{ arch }}-{{ checksum "yarn.lock" }}-{{ epoch }}
        paths:
          - *yarnpkg_cache_dir

  cmd_show_env:
    steps:
      - run:
        command: |
          yarn --version
          yarn cache dir
          node -v

  cmd_install_dependencies:
    steps:
      - run:
        command: yarn

  cmd_build:
    steps:
      - run:
        command: yarn build

  cmd_lint:
    steps:
      - run:
        command: yarn lint

  cmd_test:
    steps:
      - run:
        command: yarn test

  cmd_attach_workspace:
    steps:
      - attach_workspace:
        at: *workspace_root

  cmd_persist_dependencies_to_workspace:
    steps:
      - persist_to_workspace:
        root: *workspace_root
        paths:
          - *node_modules_dir
          - *yarnpkg_cache_dir

jobs:
  dependencies:
    executor: node_latest
    steps:
      - checkout
      - cmd_show_env
      - cmd_restore_cache
      - cmd_install_dependencies
      - cmd_save_cache
      - cmd_persist_dependencies_to_workspace

  lint:
    executor: node_latest
    steps:
      - checkout
      - cmd_attach_workspace
      - cmd_show_env
      - cmd_install_dependencies
      - cmd_lint

  test_in_node_lts:
    executor: node_lts
    steps:
      - checkout
      - cmd_attach_workspace
      - cmd_show_env
      - cmd_install_dependencies
      - cmd_build
      - cmd_test

  test_in_node_latest:
    executor: node_latest
    steps:
      - checkout
      - cmd_attach_workspace
      - cmd_show_env
      - cmd_install_dependencies
      - cmd_build
      - cmd_test

cond_filters_tags_and_branches: &cond_filters_tags_and_branches
  branches:
    only: /.*/
  tags:
    only: /.*/

workflow_test_job_conf: &workflow_test_job_conf
  requires:
    - dependencies
  filters:
    <<: *cond_filters_tags_and_branches

workflows:
  build_and_test:
    jobs:
      - dependencies:
        filters:
          <<: *cond_filters_tags_and_branches
      - lint:
        <<: *workflow_test_job_conf
      - test_in_node_lts:
        <<: *workflow_test_job_conf
      - test_in_node_latest:
        <<: *workflow_test_job_conf
